version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4004:4004"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.1'
#          memory: 256M
#        reservations:
#          cpus: '0.1'
#          memory: 128M
    volumes:
      - ./upload:/usr/src/app/uploads
    environment:
      NODE_ENV: production
      DB_HOST: bayasho_db  
      DB_PORT: 3306        
      DB_USER: root        
      DB_PASSWORD: password  
      DB_NAME: bayashop    
    networks:
      - my-network  

  bayasho_db:
    image: mysql:8.0
    container_name: bayasho_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bayashop
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.1'
#          memory: 256M
#        reservations:
#          cpus: '0.1'
#          memory: 128M
    volumes:
      - mysql_data_volume:/var/lib/mysql  
    networks:
      - my-network  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: bayasho_db  
      MYSQL_ROOT_PASSWORD: password 
    ports:
      - "8081:80"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.1'
#          memory: 256M
#        reservations:
#          cpus: '0.1'
#          memory: 128M
    volumes:
      - phpmyadmin_data_volume:/var/lib/phpmyadmin
    networks:
      - my-network  

volumes:
  mysql_data_volume: 
    driver: local

  phpmyadmin_data_volume: 
    driver: local

networks:
  my-network:  
    driver: bridge  
