version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4004:4004"
    volumes:
      - ./upload:/usr/src/app/uploads
    environment:
      NODE_ENV: production
      DB_HOST: bayasho_db  # The name of your MySQL service
      DB_PORT: 3306        # MySQL default port
      DB_USER: root        # MySQL root user
      DB_PASSWORD: password  # MySQL root password
      DB_NAME: bayashop    # The database name to connect to

  bayasho_db:
    image: mysql:8.0
    container_name: bayasho_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bayashop
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_volume:/var/lib/mysql  # Persistent volume for MySQL data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: bayasho_db  # Connects to MySQL service
      MYSQL_ROOT_PASSWORD: password  # Use the root password from MySQL
    ports:
      - "8081:80"
    volumes:
      - phpmyadmin_data_volume:/var/lib/phpmyadmin

volumes:
  mysql_data_volume:  # Define the volume for MySQL data
    driver: local

  phpmyadmin_data_volume:  # Define the volume for phpMyAdmin data
    driver: local
