version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4004:4004"
    volumes:
      - ./upload:/usr/src/app/uploads
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
