version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4004:4004"
    volumes:
      - ./upload:/usr/src/app/uploads
    environment:
      NODE_ENV: production
